version: '3'

services:
  cmake:
    container_name: bel
    build:
      context: .
      dockerfile: Dockerfile

    tty: true
    command: /bin/bash

    volumes:
      - ./src:/usr/src
      - $HOME/go:/root/go
    ports:
      - "3300:8080"
